site_name: SpaceWalks Documentation
use_directory_urls: false
theme:
  name: material
font: false
nav:
  - Spacewalks Documentation: index.md
  - Tutorial: tutorials.md
  - How-To-Guides: how-to-guide.md
  - Reference: reference.md
  - Background: explanation.md

plugins:
  - mkdocstrings

